Adds support for sam.gz and sam.xz in calculate_coverage.py
ucsd-cmi/zebra_filter pull request #1
Opened 2021-05-12 18:59 UTC by dhakim87

Right now this only works for calculate_coverage.py.  I think making something similar for filter_sam would be straightforward, definitely easy to add this exact change to read in files, but I didn't feel comfortable deciding whether output files should be zipped or not matching the input files.  

Let me know if you want something like this and I'm happy to help add it in.

2021-05-12 19:11 UTC, wasade requested changes
Just some minor items

2021-05-12 19:11 UTC, wasade commented on calculate_coverages.py
> +
...shouldn't happen but:

```suggestion
else:
    raise IOError("Unrecognized file extension on '%s'." % samfile)
```

2021-05-12 19:11 UTC, wasade commented on calculate_coverages.py
> +        with open_sam_file:
I don't think the context is necessary as the file was opened explicitly?

2021-05-12 19:11 UTC, wasade commented on calculate_coverages.py
I think an explicit close should be issued after use
```suggestion
        open_sam_file.close()
```

2021-05-12 19:40 UTC, dhakim87 commented on calculate_coverages.py
> +        with open_sam_file:
My intention was to let the with statement automatically close the open_sam_file, avoiding the need for exception handling and an explicit close() call.  Does that work?

2021-05-12 20:02 UTC, dhakim87 commented on calculate_coverages.py
> +        with open_sam_file:
with statement seems to still call __enter__ and __exit__ even if target object was constructed prior:

`class Foo:
    def __enter__(self):
        print("Entering Foo")

    def __exit__(self, exc_type, exc_val, exc_tb):
        print("Exiting Foo")


def open_it():
    print("Opening Foo")
    foo = Foo()
    print("Returning Foo")
    return foo

print("CASE 1, with open_it as foo:")
with open_it() as foo:
    print("Holding onto foo")

print("CASE 2, with existing foo:")
foo = open_it()
with foo:
    print("Holding onto foo")
`

2021-05-12 20:47 UTC, wasade commented on calculate_coverages.py
> +        with open_sam_file:
oh weird. okay

2021-05-12 20:47 UTC, wasade approved these changes

2021-05-12 20:49 UTC, wasade commented
I'm not sure who is maintainer -- @adswafford, are you good if I merge items?

2021-05-12 20:52 UTC, dhakim87 commented
Should hold off on merge until there is a strategy for adding something similar to filter_sam.py?

2021-05-18 19:05 UTC, adswafford commented
After merging other branch, conflicts with code. @dhakim87 can you have a look and resolve?

2021-05-18 21:11 UTC, dhakim87 commented
Should be resolved

2021-05-26 18:33 UTC, adswafford commented
@dhakim87 did you get a chance to update the filter_sam.py to take sam.xz and sam.gz files as well? Relatedly, do you have your code snippet for running Woltka afterward on the filtered sams that we can add to the documentation?

2021-05-26 19:07 UTC, dhakim87 commented
I've been blocked hoping to ask maintainer about choices for output file format:

If filter_sam.py is given a .sam.xz, what should it produce as output? 
- **A:** .sam 
- **B:** .sam.xz  

Will be trivial to add once that is decided.

2021-05-26 19:17 UTC, dhakim87 commented
> @dhakim87 ... Relatedly, do you have your code snippet for running Woltka afterward on the filtered sams that we can add to the documentation?

I'm not sure what you mean by this exactly.  filter_sam.py just produces new sam files, so any tool that takes a .sam will run exactly the same as before.  I've never actually run filter_sam.py, I've only looked at the coverage results and filtered the resulting biom table.  

Do you mean the code I used to import the coverage output into my mimics database for the momi tool?  That would just be converting to sql as per:

```
import sqlite3
import csv

def add_zebra():
    conn = sqlite3.connect("mimics.db")
    c = conn.cursor()
    c.execute("CREATE TABLE IF NOT EXISTS zebra(genome_id text PRIMARY KEY, covered_length int, total_length int, coverage_ratio real)")
    with open("coverage_output.tsv") as zebra_output:
        zebra_reader = csv.reader(zebra_output, delimiter='\t', quotechar='|')
        header = next(zebra_reader)
        for row in zebra_reader:
            c.execute("INSERT INTO zebra VALUES(?,?,?,?)", (row[0], row[1], row[2], row[3]))
    conn.commit()
    conn.close()
```

2021-05-26 19:40 UTC, adswafford commented
Ah, filtering that way isn't advisable imo since you don't get redistribution of the reads to the retained list of microbes. Since woltka takes sam.xz I think outputting in that format is desirable.

2021-05-26 19:48 UTC, dhakim87 commented
> Ah, filtering that way isn't advisable imo since you don't get redistribution of the reads to the retained list of microbes. Since woltka takes sam.xz I think outputting in that format is desirable.

Does woltka look over individual files or all files for a list of included matches at any point?  If not, I don't understand how it can redistribute reads in a meaningful way- all the reads associated with the genomes that don't match the threshold criteria are entirely removed in filter_sam aren't they?

2021-05-26 20:27 UTC, gregpoore commented
Does woltka look over individual files or all files for a list of included matches at any point? If not, I don't understand how it can redistribute reads in a meaningful way- all the reads associated with the genomes that don't match the threshold criteria are entirely removed in filter_sam aren't they?

Yes, but in the case where Woltka splits a read among several possible assignments, the redistribution post filtering will change versus the original assignments.

On May 26, 2021, at 2:48 PM, Daniel Hakim ***@***.******@***.***>> wrote:



Ah, filtering that way isn't advisable imo since you don't get redistribution of the reads to the retained list of microbes. Since woltka takes sam.xz I think outputting in that format is desirable.

Does woltka look over individual files or all files for a list of included matches at any point? If not, I don't understand how it can redistribute reads in a meaningful way- all the reads associated with the genomes that don't match the threshold criteria are entirely removed in filter_sam aren't they?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/ucsd-cmi/zebra_filter/pull/1*issuecomment-849070957__;Iw!!Mih3wA!TW0n6GBEINF2t6ozn5HV4Z6zFx7T8LibqAQMoW53yt09aGW_5KDicLlIHz-k8eee$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AB2W322M4ENDGXTYS63BWVLTPVGBHANCNFSM44ZFSJKA__;!!Mih3wA!TW0n6GBEINF2t6ozn5HV4Z6zFx7T8LibqAQMoW53yt09aGW_5KDicLlIH96xCKnV$>.

2021-05-26 20:53 UTC, adswafford commented
That's correct. So filtering the biom table will artificially deflate the total read count since all of the fractional assignments to zebras are discarded. If you run filter sam however and supply the output sam(.xz) to Woltka, then they will be correctly distributed. 

For a toy example, imagine 1000 reads each align to 10 different microbes. So in the biom table that read is distributed across the microbes with each one receiving 100 reads.  If you then calc coverages and eliminate 9 of those microbes from the biom table, you'll be down to 100 reads for the one remaining microbe. If you instead filter_sam.py that one microbe will now get all 1000 reads.

Does that make sense?

2021-05-26 21:12 UTC, dhakim87 commented
My gut feeling is that something is off about this high level procedure.  In the edge case that there is a read that aligns to 16 different species, none of which meet the coverage threshold, that read is silently discarded at the filter_sam layer.  Ideally that error case would bubble up through woltka by instead making woltka aware of the coverage threshold and which reference genomes pass and fail that threshold.  

That has exactly nothing to do with zip support though

2021-07-01 06:56 UTC, merged