Hashset to ranges
ucsd-cmi/zebra_filter pull request #2
Opened 2021-05-12 19:35 UTC by dhakim87

When running calculate_coverage on several thousand .sam files, I noticed the memory usage was quite high, causing me to run out of memory.  I tracked usage to the sets of integers used to keep track of coverage.  

I've added two new files, cover.py and cover_test.py.  

cover.py implements a new data structure: SortedRangeList.  This takes inclusive integer ranges and maintains the total coverage of those ranges, automatically compressing its internal representation over time.  

cover_test.py is a collection of unit tests and performance test functions to compare it against the original hashset implementation.  

Theoretical performance from cover_test is about 3x faster with 1/100 memory usage for set operations.  
Real world performance is closer to 1.2-1.5x faster for the whole program, 1/10 memory usage.  

This takes it from ~40-50GB to ~4GB for the first set of files in my use case.

2021-05-13 16:33 UTC, antgonza requested changes
Thank you @dhakim87, a few questions and suggestions.

2021-05-13 16:33 UTC, antgonza commented on calculate_coverages.py
>      file_list = glob(input + "/*.sam")
Would it be worth doing "/*.sam*" or perhaps "/*.sam" and "/*.sam.xz"? If I remember correctly wolka also support xz.

2021-05-13 16:33 UTC, antgonza commented on cover.py
> +        self.ranges.append((start,end))
Are we running flake8 or pep8 in this repo? Wondering because this line seems not compliant: no space between the , and end.

2021-05-13 16:33 UTC, antgonza commented on cover.py
> +            else:  # if end_val < r[0] - 1:
Should the comment after the else be deleted?

2021-05-13 16:33 UTC, antgonza commented on cover_test.py
> +    print("SET_ADD: ", perf_counter() - start_set)
Is this print and the other below needed? Normally tests are silent, right?

2021-05-13 16:33 UTC, antgonza commented on cover_test.py
> +from cover import SortedRangeList
Is there a reason to not use unittest?

2021-05-13 17:18 UTC, dhakim87 commented on calculate_coverages.py
>      file_list = glob(input + "/*.sam")
See my other PR: https://github.com/ucsd-cmi/zebra_filter/pull/1.  It's just not the focus of this one.

2021-05-13 17:25 UTC, dhakim87 commented on cover.py
> +        self.ranges.append((start,end))
Doesn't look like it- wouldn't be too hard to get there though, the codebase is only a few scripts.  I think its out of scope for this PR, but I'll fix up anything added in this one.

2021-05-13 17:39 UTC, dhakim87 commented on cover.py
> +            else:  # if end_val < r[0] - 1:
Getting the indexing right was tricky, I think a reminder that it will join not just [x, y] [y, z] but [x, y] [y+1, z] is helpful.

2021-05-13 17:45 UTC, dhakim87 commented on cover_test.py
> +    print("SET_ADD: ", perf_counter() - start_set)
First and second could be made into pure unit tests.  But second, and also third also function as performance tests to show the improvement.  There was no unit testing framework in place as far as I could tell, and it seemed unnecessary to add one for a repo with two scripts in it.  

I wasn't sure if cover_test.py would be deleted and the 60 lines of cover.py added to the top of calculate_coverage.py.  

If we do go with a unit test framework, is there a reason unit tests should be silent?

2021-05-13 17:46 UTC, dhakim87 commented on cover_test.py
> +from cover import SortedRangeList
None afaik, but no framework was in place and I didn't feel comfortable deciding on one in this PR.

2021-05-13 18:28 UTC, antgonza commented on cover.py
> +            else:  # if end_val < r[0] - 1:
Got it, not really important but perhaps worth merging to the comment below.

2021-05-13 18:28 UTC, antgonza commented on cover_test.py
> +from cover import SortedRangeList
Got it, it will be good to decide that before adding more code ... could you open an issue so it can be discussed?

2021-05-13 18:28 UTC, antgonza commented on cover_test.py
> +    print("SET_ADD: ", perf_counter() - start_set)
IMOO if the idea is to test the performance of a code, you need to add a test for that specifically, and the specific test will depend on how you define "better", for example if better is that `x > y`, then the test should be something like `self.assertTrue(x > y)`.

Now, I have never seen prints in tests before, except for debugging, because normally the idea is that nobody should be looking at the output of the tests to confirm that things are good/bad but have tests to check that ...

2021-05-13 18:28 UTC, antgonza commented on cover_test.py
> +from cover import SortedRangeList
It will also be nice to discuss if the repo needs `continuous integration` so flake8 and the testing can be run automatically.

2021-05-14 13:17 UTC, antgonza approved these changes
Thank you @dhakim87.

IMOO #3 and #4 should be decided before merging this code, and more because this push: <img width="222" alt="Screen Shot 2021-05-14 at 7 15 20 AM" src="https://user-images.githubusercontent.com/2014559/118275868-3999de00-b484-11eb-8676-01901745289e.png"> shows why is important to have CI. However, I understand that this might still be a POC. @wasade, could you take a look? Thank you.

2021-05-14 15:21 UTC, wasade commented
Thanks! What I propose is we merge this now, discuss the longer term plan for this repository at the thinktank meeting this Monday, and proceed from there (@dhakim87, please let me know if you don't know what I'm talking about). The codebase is small enough that resolving #3 and #4 outside of this PR wouldn't be that bad. Does that sound reasonable?

2021-05-14 19:02 UTC, dhakim87 commented
I'm fine to see it merged in - it successfully ran on the several thousand sam files of my dataset after these changes.

2021-05-18 19:04 UTC, merged